FROM pablozaiden/typescript

ONBUILD COPY . /app
ONBUILD RUN yarn install
# [HACK]: Until the types definition work properly, remove incompatible node definitions
ONBUILD RUN mv /app/node_modules/@types/node /
ONBUILD RUN rm -rf `find /app/node_modules/@types/ -iname node`
ONBUILD RUN mv /node /app/node_modules/@types/
# [/HACK] 
ONBUILD RUN tsc -p .
